### ISSUE TITLE
How can I load data

### ISSUE THREAD

**Issue by SunShuoyue** [TobiasLee/Text-Classification#10]
when I run the statement, it gives me an NameError
"NameError: name 'FLAGS' is not defined"
Could you please tell me what is 'FLAGS' referring to?

**Comment by Hsuzy** [comment]
I can't load the dataset.Could you offer an address or a link?Thank you.

**Comment by TobiasLee** [comment]
@SunShuoyue  Sorry, the FLAGS is used for configuring some parameters, you can change it by yourself.

**Comment by TobiasLee** [comment]
@Hsuzy   I uploaded it to [Baidu Yun](https://pan.baidu.com/s/1WRj2w-VTz6-dY8kCcyir9w)

**Comment by TgDots** [comment]
It's still an error link from the  "Baidu Yun" .Could you offer the dataset again? Thanks

**Comment by TobiasLee** [comment]
Try [Google Drive](https://drive.google.com/file/d/1Wna0X8PAvmE0SToo67lPeWW1JQMd-uy-/view?usp=sharing)

**Comment by ftk1000** [comment]
to get data, remove ", test_with_fake_data=FLAGS.test_with_fake_data" and simply run

>>> dbpedia = tf.contrib.learn.datasets.load_dataset('dbpedia')

that will create ./dbpedia_data folder with data files in it
