### ISSUE TITLE
Test Accuracy	is lower than the Performance in Readme

### ISSUE THREAD

**Issue by Alarical** [TobiasLee/Text-Classification#12]
Epoch 19 start !
Train Epoch time:  108.163 s
validation accuracy: 0.932 
Epoch 20 start !
Train Epoch time:  107.236 s
validation accuracy: 0.936 
Training finished, time consumed :  2188.0112912654877  s
Start evaluating:  

Test accuracy : **93.619048 %**

This is the performance in **attn_bi_lstm.py。**  Why it’s lower than 98.23 % in readme?
Thanks!

**Comment by TobiasLee** [comment]
Hi,  the model isn't trained with the full data to provide a quick test of the model, so the performance is lower than that in README.
Change the `sample_ratio` to 1.0 to utilize full data to train the model:
> x_train, y_train = load_data("../dbpedia_data/dbpedia_csv/train.csv", sample_ratio=1e-2, one_hot=False)
