### ISSUE TITLE
validation and testing accuracy=0 

### ISSUE THREAD

**Issue by saja1994** [TobiasLee/Text-Classification#13]
First of all thank you for your effort. My problem is that the implementation run correctly when I use dbpedia dataset, but when I try to my dataset I got an accuracy of 0. My dataset is in the Arabic language.

**Comment by TobiasLee** [comment]
Sorry, I did not do experiments on the Arabic language dataset. As you said the implementation can get expected results on the Dbpedia dataset, so the problem may attribute to
the data preprocessing process.

**Comment by saja1994** [comment]
Thanks for your response, I will try to edit the preprocessing code.
Regards,
