### ISSUE TITLE
attn_bi_lstm.py模型的y_hat那里是不是写错了？

### ISSUE THREAD

**Issue by waywaywayw** [TobiasLee/Text-Classification#2]
https://github.com/TobiasLee/Text-Classification/blob/8fd3a7bfb38cb6360c58d0f71488b7946e313d06/models/attn_bi_lstm.py#L48

这里马上要求出y的预测值了，而类别只有15个。而不是32个。
这里FC_W 的shape应该是：
[self.hidden_size, self.n_class]
而不是
[self.hidden_size, self.max_len]
吧？下面的FC_b 也是同样的问题。
老哥来看看是不是有问题，还是我理解错了~ @TobiasLee

**Comment by TobiasLee** [comment]
是的 谢谢！ 已经修改啦~
