### ISSUE TITLE
Can i ask the editionof the dbpediafile

### ISSUE THREAD

**Issue by alice-cool** [TobiasLee/Text-Classification#20]
download it from Baidu Yun.

**Comment by TobiasLee** [comment]
Hi, I'am not sure which edition it is. The dataset was originally downloaded from old tensorflow api. You may find the edition information by checking the legacy tensorflow 1.4 doc?

**Comment by alice-cool** [comment]
Thanks your timely reply. Thanks again.&nbsp;



---Original---
