### ISSUE TITLE
adversarial_abblstm.py  - validation accuracy: 0% / test accuracy: 0% 

### ISSUE THREAD

**Issue by bluebyte9001** [TobiasLee/Text-Classification#5]
I am running your code without modifications on the dbpedia dataset and is receiving non-valid results as follows:

..
Validation accuracy: 0.000 
Training finished, time consumed :  133.85788369178772  s
Start evaluating:  
Test accuracy : 0.000000 %

**Comment by TobiasLee** [comment]
I think the problem may related to the issue #4  , and I fixed the problem by changing the shuffle function, and below if my result:
> Epoch 1 start !
Train Epoch time:  31.915 s
validation accuracy: 0.732 
Epoch 2 start !
Train Epoch time:  32.457 s
validation accuracy: 0.840
